name: run main.py

on:
  schedule:
    - cron: '*/5 * * * *' # Every Day at 4PM NST (10:15am UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        run: 
          python main.py
          
      - name: commit files
        run: |
          git config --local user.email "sumanaryal83@gmail.com"
          git config --local user.name "aryalsuman"
          git add .
          git commit -m "Data Scraped Sucessfully" -a
          git push origin main
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
